version: '3.7'
services:
  strapi:
    image: strapi/strapi
    # command: yarn start
    env_file: 
      - .strapi.env
    volumes:
      - ./app:/srv/app
    ports:
      - 20101:1337
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file: 
      - .postgres.env
    volumes:
      - ./data:/var/lib/postgresql/data

  backend:
    image: pan93412/ciscc-backend:1.0
    ports:
      - 20100:3000
    env_file:
      - .backend.env
